module.exports = {
    types: [{
        name: '生日礼金',
        type: 1,
        code: 'present',
    }, {
        name: '投资',
        type: 1,
        code: 'honor',
    }, {
        name: '礼物',
        type: 1,
        code: 'gift',
    }, {
        name: '电费',
        type: 1,
        code: 'electry',
    }, {
        name: '水费',
        type: 1,
        code: 'water',
    }, {
        name: '旅游',
        type: 1,
        code: 'screen',
    }, {
        name: '餐饮',
        type: 1,
        code: 'eat',
    }, {
        name: '唱歌',
        type: 1,
        code: 'sing',
    }, {
        name: '购物',
        type: 1,
        code: 'shopping',
    }, {
        name: '红包',
        type: 1,
        code: 'pocket',
    }, {
        name: '电影',
        type: 1,
        code: 'movie',
    }, {
        name: '房租',
        type: 1,
        code: 'house',
    }, {
        name: '通讯',
        type: 1,
        code: 'tel',
    }, {
        name: '交通',
        type: 1,
        code: 'bus',
    }, {
        name: '食品饮料',
        type: 1,
        code: 'drink',
    }, {
        name: '日用品',
        type: 1,
        code: 'daily',
    }, {
        name: '医疗',
        type: 1,
        code: 'hospital',
    }, {
        name: '服饰箱包',
        type: 1,
        code: 'bag',
    }, {
        name: '出差',
        type: 1,
        code: 'plane',
    }, {
        name: '食品',
        type: 1,
        code: 'food',
    }, {
        name: '化妆品',
        type: 1,
        code: 'lip',
    }, {
        name: '收款',
        type: 0,
        code: 'earn',
    }, {
        name: '其他收入',
        type: 0,
        code: 'money',
    }, {
        name: '工资',
        type: 0,
        code: 'fee',
    }],
};
