module.exports = {
    types: [{
        name: '生日礼金',
        type: 1,
        code: 'icon-present',
    }, {
        name: '投资',
        type: 1,
        code: 'icon-honor',
    }, {
        name: '礼物',
        type: 1,
        code: 'icon-gift',
    }, {
        name: '电费',
        type: 1,
        code: 'icon-electry',
    }, {
        name: '水费',
        type: 1,
        code: 'icon-water',
    }, {
        name: '旅游',
        type: 1,
        code: 'icon-screen',
    }, {
        name: '餐饮',
        type: 1,
        code: 'icon-eat',
    }, {
        name: '唱歌',
        type: 1,
        code: 'icon-sing',
    }, {
        name: '购物',
        type: 1,
        code: 'icon-shopping',
    }, {
        name: '红包',
        type: 1,
        code: 'icon-pocket',
    }, {
        name: '电影',
        type: 1,
        code: 'icon-movie',
    }, {
        name: '房租',
        type: 1,
        code: 'icon-house',
    }, {
        name: '通讯',
        type: 1,
        code: 'icon-tel',
    }, {
        name: '交通',
        type: 1,
        code: 'icon-bus',
    }, {
        name: '食品饮料',
        type: 1,
        code: 'icon-drink',
    }, {
        name: '日用品',
        type: 1,
        code: 'icon-daily',
    }, {
        name: '医疗',
        type: 1,
        code: 'icon-hospital',
    }, {
        name: '服饰箱包',
        type: 1,
        code: 'icon-bag',
    }, {
        name: '出差',
        type: 1,
        code: 'icon-plane',
    }, {
        name: '食品',
        type: 1,
        code: 'icon-food',
    }, {
        name: '化妆品',
        type: 1,
        code: 'icon-lip',
    }, {
        name: '收款',
        type: 0,
        code: 'icon-earn',
    }, {
        name: '其他收入',
        type: 0,
        code: 'icon-money',
    }, {
        name: '工资',
        type: 0,
        code: 'icon-fee',
    }],
};
