module.exports = {
    types: [{
        name: '生日礼金',
        type: 1,
        code: 'present',
        tid: 1,
    }, {
        name: '投资',
        type: 1,
        code: 'honor',
        tid: 2,
    }, {
        name: '礼物',
        type: 1,
        code: 'gift',
        tid: 3,
    }, {
        name: '电费',
        type: 1,
        code: 'electry',
        tid: 4,
    }, {
        name: '水费',
        type: 1,
        code: 'water',
        tid: 5,
    }, {
        name: '旅游',
        type: 1,
        code: 'screen',
        tid: 6,
    }, {
        name: '餐饮',
        type: 1,
        code: 'eat',
        tid: 7,
    }, {
        name: '唱歌',
        type: 1,
        code: 'sing',
        tid: 8,
    }, {
        name: '购物',
        type: 1,
        code: 'shopping',
        tid: 9,
    }, {
        name: '红包',
        type: 1,
        code: 'pocket',
        tid: 10,
    }, {
        name: '电影',
        type: 1,
        code: 'movie',
        tid: 11,
    }, {
        name: '房租',
        type: 1,
        code: 'house',
        tid: 12,
    }, {
        name: '通讯',
        type: 1,
        code: 'tel',
        tid: 13,
    }, {
        name: '交通',
        type: 1,
        code: 'bus',
        tid: 14,
    }, {
        name: '食品饮料',
        type: 1,
        code: 'drink',
        tid: 15,
    }, {
        name: '日用品',
        type: 1,
        code: 'daily',
        tid: 16,
    }, {
        name: '医疗',
        type: 1,
        code: 'hospital',
        tid: 17,
    }, {
        name: '服饰箱包',
        type: 1,
        code: 'bag',
        tid: 18,
    }, {
        name: '出差',
        type: 1,
        code: 'plane',
        tid: 19,
    }, {
        name: '食品',
        type: 1,
        code: 'food',
        tid: 20,
    }, {
        name: '化妆品',
        type: 1,
        code: 'lip',
        tid: 21,
    }, {
        name: '收款',
        type: 0,
        code: 'earn',
        tid: 22,
    }, {
        name: '其他收入',
        type: 0,
        code: 'money',
        tid: 23,
    }, {
        name: '工资',
        type: 0,
        code: 'fee',
        tid: 24,
    }],
};
